server:
  port: 8080

factservice:
  host: fact-service:8080

fibservice:
  host: fib-service:8080
logging:
  level:
    org:
      springframework: DEBUG

---
opentracing:
  jaeger:
    service-name: Compute Service
    udp-sender:
      host: jaeger-agent
      port: 6831